# Generated by Django 3.1 on 2022-07-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
