# Generated by Django 3.1 on 2022-08-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
