# Generated by Django 3.1 on 2022-08-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
